var panjang,luas,lebar;
panjang=prompt("Masukkan Panjang:")||'';
lebar=prompt("Masukkan Lebar:")||'';
luas=panjang*lebar;
document.writeln("<table border='1'>");
document.writeln("<tr>");
document.writeln("<td>Variable</td><td>datamsaukan</td><td>keseluruhan</td></tr>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td>panjang</td> <td></td> <td></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td>" + panjang + "</td> <td></td> <td></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td>lebar</td> <td>"+lebar+"</td> <td></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td>Luas</td> <td></td> <td></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td>Panjang*Lebar</td> <td>" + luas + "</td> <td></td>");
document.writeln("</tr>");
document.writeln("</table>");
